# Generated by Django 6.0.7 on 2026-08-11 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("KILO", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                        ],
                        default="UNIDAD",
                        max_length=10,
                    ),
                ),
                ("stock_minimo", models.PositiveIntegerField(default=0)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="catalogo.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
    ]
