# Generated by Django 6.0.7 on 2026-08-11 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacenes", "0001_initial"),
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_movimiento",
                        to="catalogo.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("numero", models.CharField(blank=True, max_length=15, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("TRASLADO", "Traslado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADO", "Confirmado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=200)),
                (
                    "almacen_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_entrada",
                        to="almacenes.almacen",
                    ),
                ),
                (
                    "almacen_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_salida",
                        to="almacenes.almacen",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
