# Generated by Django 6.0.7 on 2026-08-11 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movimientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="detallemovimiento",
            name="movimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="movimientos.movimiento",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallemovimiento",
            constraint=models.UniqueConstraint(
                fields=("movimiento", "producto"), name="producto_unico_por_movimiento"
            ),
        ),
    ]
